### ISSUE TITLE
kernel modules use spdx standard for copyright comments

### ISSUE THREAD

**Issue by dtaht** [ewsi/macremapper#2]
see: https://spdx.org/

**Comment by csonsino** [comment]
I *think* that I did that correctly, but I am not a lawyer :)

**Comment by csonsino** [comment]
@dtaht Please take a look at PR #3 and let me know if additional work needs to be done to resolve this issue.  Otherwise, I'll go ahead and merge in the changes.

**Comment by csonsino** [comment]
Merged in PR #3
